<!ELEMENT Point EMPTY>
        <!ATTLIST Point
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT ShipPoint EMPTY>
        <!ATTLIST ShipPoint
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT Ship (index, length, start, vertical, destroyed, Points)>
        <!ELEMENT index (#PCDATA)>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT start EMPTY>
        <!ATTLIST start
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >
        <!ELEMENT vertical (#PCDATA)>
        <!ELEMENT destroyed (#PCDATA)>
        <!ELEMENT Points (ShipPoint*)>

        <!ELEMENT Ships (Ship*)>
        <!ELEMENT Destroyed (Point*)>
        <!ELEMENT Missed (Point*)>

        <!ELEMENT Board (Ships, Destroyed, Missed)>


        <!ELEMENT AssemblyReadyMessage (Board)>
        <!ATTLIST AssemblyReadyMessage
                action CDATA #REQUIRED
                correlationId CDATA #IMPLIED
                >