<!ELEMENT Point EMPTY>
        <!ATTLIST Point
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT ShipPoint EMPTY>
        <!ATTLIST ShipPoint
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT index (#PCDATA)>
        <!ELEMENT length (#PCDATA)>
        <!ELEMENT start EMPTY>
        <!ATTLIST start
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >
        <!ELEMENT vertical (#PCDATA)>
        <!ELEMENT destroyed (#PCDATA)>
        <!ELEMENT Points (ShipPoint*)>

        <!ELEMENT Ship (index, length, start, vertical, destroyed, Points)>

        <!ELEMENT IdlePoints (IdlePoint*)>
        <!ELEMENT IdlePoint EMPTY>
        <!ATTLIST IdlePoint
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT result (point, missed, DestroyedShip?, IdlePoints?)>

        <!ELEMENT point EMPTY>
        <!ATTLIST point
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >
        <!ELEMENT missed (#PCDATA)>
        <!ELEMENT DestroyedShip (index, length, start, vertical, destroyed, Points)>

        <!ELEMENT GameUpdateOpponentMessage (result)>
        <!ATTLIST GameUpdateOpponentMessage
                action CDATA #REQUIRED
                correlationId CDATA #REQUIRED
                >