<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="PointType">
        <xs:attribute name="x" type="xs:int" use="required"/>
        <xs:attribute name="y" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="ShipType">
        <xs:sequence>
            <xs:element name="index" type="xs:int"/>
            <xs:element name="length" type="xs:int"/>
            <xs:element name="start" type="PointType"/>
            <xs:element name="vertical" type="xs:boolean"/>
            <xs:element name="destroyed" type="xs:boolean"/>
            <xs:element name="Points" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ShipPoint" type="PointType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AttackResultType">
        <xs:sequence>
            <xs:element name="point" type="PointType"/>
            <xs:element name="missed" type="xs:boolean"/>
            <xs:element name="DestroyedShip" type="ShipType" minOccurs="0"/>
            <xs:element name="IdlePoints" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="IdlePoint" type="PointType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="GameAttackResultMessage">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="result" type="AttackResultType"/>
            </xs:sequence>
            <xs:attribute name="action" type="xs:string" use="required"/>
            <xs:attribute name="correlationId" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>