package by.bsu.waterships.shared.types;

public enum MessageCode {
    RESULT,
    PING,
    HANDSHAKE,
    INTERRUPT,
    DISCONNECT,

    INTRODUCTION_START,
    INTRODUCTION_SUBMIT_PROGRESS,
    INTRODUCTION_UPDATE_OPPONENT,
    INTRODUCTION_END,

    ASSEMBLY_PLACE_SHIP,
    ASSEMBLY_UPDATE_OPPONENT,
    ASSEMBLY_READY,

    GAME_BEGIN,
    GAME_READY,
    GAME_TURN,
    GAME_ATTACK,
    GAME_UPDATE_OPPONENT,
    GAME_FINISH
}
