<!ELEMENT Point EMPTY>
        <!ATTLIST Point
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT ShipPoint EMPTY>
        <!ATTLIST ShipPoint
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT Ship (start, points)>
        <!ATTLIST Ship
                index CDATA #REQUIRED
                length CDATA #REQUIRED
                vertical CDATA #REQUIRED
                destroyed CDATA #REQUIRED
                >
        <!ELEMENT start EMPTY>
        <!ATTLIST start
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >
        <!ELEMENT points (ShipPoint*)>

        <!ELEMENT Ships (Ship*)>
        <!ELEMENT Destroyed (Point*)>
        <!ELEMENT Missed (Point*)>

        <!ELEMENT Board (Ships, Destroyed, Missed)>


        <!ELEMENT AssemblyReadyMessage (Board)>
        <!ATTLIST AssemblyReadyMessage
                action CDATA #REQUIRED
                correlationId CDATA #IMPLIED
                >