<!ELEMENT Point EMPTY>
        <!ATTLIST Point
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT ShipPoint EMPTY>
        <!ATTLIST ShipPoint
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT IdlePoints (IdlePoint*)>
        <!ELEMENT IdlePoint EMPTY>
        <!ATTLIST IdlePoint
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >

        <!ELEMENT DestroyedShip (start, points)>
        <!ATTLIST DestroyedShip
                index CDATA #REQUIRED
                length CDATA #REQUIRED
                vertical CDATA #REQUIRED
                destroyed CDATA #REQUIRED
                >
        <!ELEMENT start EMPTY>
        <!ATTLIST start
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >
        <!ELEMENT points (ShipPoint*)>

        <!ELEMENT result (point, missed, DestroyedShip?, IdlePoints?)>

        <!ELEMENT point EMPTY>
        <!ATTLIST point
                x CDATA #REQUIRED
                y CDATA #REQUIRED
                >
        <!ELEMENT missed (#PCDATA)>

        <!ELEMENT GameUpdateOpponentMessage (result)>
        <!ATTLIST GameUpdateOpponentMessage
                action CDATA #REQUIRED
                correlationId CDATA #IMPLIED
                >